### PR TITLE
New line options

### PR DESCRIPTION
**Pull request by ShahriarKh**
I expanded the "function" syntax to allow more options:
`color`, `graphType`, `nSamples`, `range` and `closed`.

With these new options, functions can be written like:
```
fn=x+12@color=green@graphType=polyline@range=[2,8]
```
and the spacing and the order don't matter:
```
color = #4390ba @ range =[2 ,15] @graphType =polyline@fn = x ^ PI
```

I chose `@` as a separator because other characters are likely to appear in math equations. Also, the `#` may appear in `color` because it also accepts HEX codes.

### CODE REVIEW

**Comment by leonhma** [comment]
All right I have to check and try this...

**Comment by leonhma** [comment]
First of all, this is a great idea to have some more customizability for your plots. That being said, the previous format (`f(x)=...`) doesn't work anymore. I am fine with having a not-so-human-friendly format in the code block that gets pasted into the markdown, but I think this is more technical than the average user of the GUI expects. Maybe I could try building a list thing (see screenshot, not bad for my first time using figma, eh?), but that would take some time as I am currently busy with exams and school-related stuff...

image

**Comment by ShahriarKh** [comment]
Surely, we need the GUI, and not just for non-tech-savvy users. But on the other hand, most of (if not all) Obsidian users know basic markdown, and I think the syntax is fairly simple to learn:
```
property=value @ property2=value2 @ ...
```
So, why not have both? 🙂

**Comment by leonhma** [comment]
I would say we use the new syntax in the markdown code block. The GUI is just a Zero-Code way for users to generate such a code block. So zero code GUI and your syntax in the markdown code block? I'll merge yours and then go from there with the GUI. Sounds good?

**Comment by leonhma** [comment]
I would say we use the new syntax in the markdown code block. The GUI is just a Zero-Code way for users to generate such a code block. So zero code GUI and your syntax in the markdown code block? I'll merge yours and then go from there with the GUI. Sounds good?

**Comment by ShahriarKh** [comment]
Exactly!

**Comment by leonhma** [comment]
Okay. I figured out why I didn't release this yet. The new syntax is handy but also incompatible with the old format. If we release this now, all existing code blocks would break and I presume the majority of the current 2,800 users won't be happy. As I said, I am working on version 2 of this plugin, which will have all of these features and more. I can't say when v2 will be released, but it's on my list. Here's what the functions list currently looks like on the `v2` branch:
Screenshot 2023-03-04 10 05 18

**Comment by ShahriarKh** [comment]
This looks really good!

**Pull request merged**
